config/routes.rb
Tanapp::Application.routes.draw do
  resources :contacts, only: [:new, :create]
  resources :visitors, only: [:new, :create]
  root to: 'visitors#new'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_no_table

  # column :name, :string
  column :email, :string
  # column :content, :string

  # validates_presence_of :name
  validates_presence_of :email
  # validates_presence_of :content
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  # validates_length_of :content, :maximum => 500

=begin commenting out spreadsheet updating with contact info

   def update_spreadsheet
    connection = GoogleDrive.login(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])
    ss = connection.spreadsheet_by_title('Learn-Rails-Example')
    if ss.nil?
      ss = connection.create_spreadsheet('Learn-Rails-Example')
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws[last_row, 1] = Time.new
    ws[last_row, 2] = self.name
    ws[last_row, 3] = self.email
    ws[last_row, 4] = self.content
    ws.save
=end

  def subscribe
    mailchimp = Gibbon::API.new
    result = mailchimp.lists.subscribe({
      :id => ENV['MAILCHIMP_LIST_ID'],
      :email => {:email => self.email},
      :double_optin => false,
      :update_existing => true,
      :send_welcome => true
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end


end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  has_no_table
  
  column :email, :string
  validates_presence_of :email
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i

  def subscribe
    mailchimp = Gibbon::API.new
    result = mailchimp.lists.subscribe({
      :id => ENV['MAILCHIMP_LIST_ID'],
      :email => {:email => self.email},
      :double_optin => false,
      :update_existing => true,
      :send_welcome => true
    })
    Rails.logger.info("Subscribed #{self.email} to MailChimp") if result
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

=begin
  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.update_spreadsheet
      UserMailer.contact_email(@contact).deliver
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
    else
      render :new
    end
  end

=end

  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      @contact.subscribe
      flash[:notice] = "Signed up #{@contact.email}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

#  def secure_params
#    params.require(:contact).permit(:name, :email, :content)
#  end

  def secure_params
    params.require(:contact).permit(:email)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(secure_params)
    if @visitor.valid?
      @visitor.subscribe
      flash[:notice] = "Signed up #{@visitor.email}."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def secure_params
    params.require(:visitor).permit(:email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact | The Tanning Emporium<% end %>
<div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Contact <strong>The Emporium</strong></h2>
            <hr>
          </div>
          <div class="col-md-8">
            <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
            <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?ie=UTF8&amp;hl=en&amp;oe=UTF8&amp;msa=0&amp;msid=206583218757632647289.0004efcc14cb891737492&amp;t=m&amp;ll=40.599641,-79.946383&amp;spn=0.00391,0.006866&amp;z=17&amp;output=embed"></iframe>
          </div>
          <div class="col-md-4">
            <p>Phone: <strong>724.444.8090</strong></p>
            <p>Hours: <br>Mon-Thurs: <strong>10am-9pm</strong><br>
                      Fri-Sat: <strong>10am-7pm</strong>
                      <br>Sun: <strong>10am-4pm</strong></p>
            <p>Email: <br> <strong>info@thetanningemporium.com</strong></p>
            <p>Address: <strong>Landmark Plaza<br>4848 William Flynn Hwy<br>Allison Park, PA 15101</strong></p>
          <hr>
            <div class="col-md-5" "image-border" "image-left">
              <a href="http://www.facebook.com/tanningemporium" target="_blank">
              <img src="http://static.viewbook.com/images/social_icons/facebook_32.png"></a>
              <div class="text-center"><h6>Like Us on <strong>Facebook</strong></h6></div>
            </div>
            <div class="col-md-5" "image-border" "image-left">
              <a href="http://www.twitter.com/tanningemporium" target="_blank">
              <img src="http://static.viewbook.com/images/social_icons/twitter_32.png"/></a>
              <div class="text-center"><h6>Follow Us on <strong>Twitter</strong></h6></div>
            </div>
              <h6 class="text-left"><em><strong>Exclusive Social Media Coupons!!</strong></em></h6>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>

      <div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">News<strong>letter</strong></h2>
            <hr>
            <p class="text-center">Sign up for our newsletter and we'll make it worth your while. Get weekly and monthly coupons, info on upcoming events, and preferred customer rewards! It only takes a few seconds.</p>
          </div>
        </div>
      </div>

<section>
  <div class="column">
    <h2>Stay in touch.</h2>
  </div>
  <div class="column">
    <div class="form-centered">
      <%= simple_form_for @contact do |form| %>
        <%= form.error_notification %>
        <%= form.input :email, label: false, :placeholder => 'Your email address...' %>
        <br/>
        <%= form.button :submit, "Sign Up Today", :class => "submit" %>
      <% end %>
    </div>
  </div>
</section>
<br>
<br>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <%= render 'layouts/navigation_links' %>
        </ul>
      </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<!-- Collect the nav links, forms, and other content for toggling -->
<li><%= link_to 'Home', new_visitor_path %></li>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>
<!-- <li><%= link_to 'Blog', page_path('blog') %></li> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tanapp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tanapp" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    
     <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="css/business-casual.css" rel="stylesheet">
  </head>
  <body>
    <div class="brand">The Tanning Emporium</div>
    <div class="address-bar">Landmark Plaza | 4848 William Flynn Hwy | Allison Park, Pennsylvania 15101 | 724-444-8090</div>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
        <div class="container">
          <%= yield %>
        </div>
    <footer>
      <div class="container">
        <div class="row">
          <p class="text-center"><em>We are a licensed nail salon looking for a nail technician, apply within.</em><br>The Tanning Emporium&copy;</p>
        </div>
      </div>
    </footer>
    </main>
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About | The Tanning Emporium<% end %>
<h3></h3>
<div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">About <strong>The Tanning Emporium</strong></h2>
            <hr>
          </div>
          <div class="col-md-6">
            <img class="img-responsive img-border-left" src="/assets/about-girls.jpg">
          </div>
          <div class="col-md-6">
            <p>With over thirty years of experience in the tanning industry, no one understands your needs and expectations better than us.<p>
            <p>Our knowledge has given us the tools necessary to satisfy you, the customer, by providing the most essential assets of a luxurious tan.</p>
            <hr>
            <h5><em><strong>Cutting Edge Tanning Beds:</em></strong></h5>
            <p>We offer an array of light intensities and options via our 15 bed selection. In addition, we have a state-of-the-art <strong>sunless </strong>spray tanning booth from VersaSpa&copy;; the current leaders in their field.</p>
            <h5><em><strong>We Carry Top Brand Lotions:</em></strong></h5>
            <p>The extensive collection of tanning lotions and skin products available are the perfect compliment. If your preferred product isn't in store, we'd be happy to obtain it for you; just ask one of our team members!</p>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <br>
      <br>
      <br>
      <div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Products & <strong>Partners</strong></h2>
            <hr>
          </div>
          <div class="col-sm-4 text-center">
              <img class="img-responsive img-border" src="/assets/about-logos.jpg">
              <h3><small></small></h3>
          </div>
          <div class="col-sm-4 text-center">
              <img class="img-responsive img-border" src="/assets/about-lotions2.jpg">
              <h3><small></small></h3>
          </div>
          <div class="col-sm-4 text-center">
              <img class="img-responsive" src="/assets/about-versaspa.jpg">
              <h3><small></small></h3>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
    <br>
    <br>

app/views/pages/blog.html.erb
      <div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Company <strong>blog</strong></h2>
            <hr>
          </div>
          <div class="col-lg-12 text-center">
            <img class="img-responsive img-border img-full" src="images/slide-1.jpg">
            <h2>Post Title<br><small>October 13, 2013</small></h2>
            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            <a href="#" class="btn btn-default btn-lg">Read More</a>
            <hr>
          </div>
          <div class="col-lg-12 text-center">
            <img class="img-responsive img-border img-full" src="assets/images/slide-2.jpg">
            <h2>Post Title<br><small>October 13, 2013</small></h2>
            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            <a href="#" class="btn btn-default btn-lg">Read More</a>
            <hr>
          </div>
          <div class="col-lg-12 text-center">
            <img class="img-responsive img-border img-full" src="images/slide-3.jpg">
            <h2>Post Title<br><small>October 13, 2013</small></h2>
            <p>Lid est laborum dolo rumes fugats untras. Etharums ser quidem rerum facilis dolores nemis omnis fugats vitaes nemo minima rerums unsers sadips amets. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
            <a href="#" class="btn btn-default btn-lg">Read More</a>
            <hr>
          </div>
          <div class="col-lg-12 text-center">
            <ul class="pager">
              <li class="previous"><a href="#">&larr; Older</a></li>
              <li class="next"><a href="#">Newer &rarr;</a></li>
            </ul>
          </div>
        </div>
      </div>

app/views/pages/new.html.erb
<% content_for :title do %>Contact<% end %>
<div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Contact <strong>business casual</strong></h2>
            <hr>
          </div>
          <div class="col-md-8">
            <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
            <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
          </div>
          <div class="col-md-4">
            <p>Phone: <strong>555.519.2013</strong></p>
            <p>Email: <strong>feedback@startbootstrap.com</strong></p>
            <p>Address: <strong>The Plaza<br>5483 Start Bootstrap Ave.<br>Beverley Hills, CA 26829</strong></p>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>

      <div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Contact <strong>form</strong></h2>
            <hr>
            <p>This contact form is just the form elements, it is not a working form. You will have to make the form work by yourself, or take it out if you can't figure out how to make it work.</p>
                <form role="form">
                  <div class="row">
                    <div class="form-group col-lg-4">
                      <label>Name</label>
                      <input type="text" class="form-control">
                    </div>
                    <div class="form-group col-lg-4">
                      <label>Email Address</label>
                      <input type="email" class="form-control">
                    </div>
                    <div class="form-group col-lg-4">
                      <label for="input3">Phone Number</label>
                      <input type="phone" class="form-control">
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group col-lg-12">
                      <label>Message</label>
                      <textarea class="form-control" rows="6"></textarea>
                    </div>
                    <div class="form-group col-lg-12">
                      <input type="hidden" name="save" value="contact">
                      <button type="submit" class="btn btn-default">Submit</button>
                    </div>
                </div>
              </form>
          </div>
        </div>
      </div>
<h3>Contact</h3>
<div class="form">
  <%= simple_form_for @contact do |form| %>
    <%= form.error_notification %>
    <%= form.input :name, autofocus: true %>
    <%= form.input :email %>
    <%= form.input :content, as: :text %>
    <%= form.button :submit, 'Submit', class: 'submit' %>
  <% end %>
</div>

app/views/visitors/new.html.erb
<% content_for :title do %>Home | The Tanning Emporium<% end %>
<% content_for :description do %>Tanning Emporium Website<% end %>
<div class="row">
  <div class="box">
    <div class="col-lg-12 text-center">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators hidden-xs">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
              </ol>
            
              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                <div class="item active">
                  <img class="img-responsive img-full" src="/assets/banner-logo.jpg" >
                </div>
                <div class="item">
                  <img class="img-responsive img-full" src="/assets/banner-sky.jpg" >
                </div>
                <div class="item">
                  <img class="img-responsive img-full" src="/assets/banner-bed.jpg" >
                </div>
              </div>
            
              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="icon-prev"></span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="icon-next"></span>
              </a>
            </div>
            <h1><small>Welcome To</small><br><span class="brand-name">The Tanning Emporium</span><hr class="tagline-divider"><small><strong></strong></small></h1>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Come get a tan <strong>worth showing off.</strong></h2>
            <hr>
            <img class="img-responsive img-border img-left" src="/assets/TanningBed.jpg">
            <hr class="visible-xs">
            <p>Here at The Tanning Emporium our goal is simple; provide our customers with a luxurious experience and a standard of service excellence. We understand the tanning business and the characteristics of a fulfilling, relaxing suntan. Getting a tan is about more than the darkening of skin, but also the brief, important moment of serenity in which you can enjoy the therapeutic nature of our services. We guarantee that our customer's will feel rejuvenated and have the best looking skin around.</p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="box">
          <div class="col-lg-12">
            <hr>
            <h2 class="intro-text text-center">Be the first to know about <strong>Fantastic Deals and Customer Rewards!</strong></h2>
            <hr>
            <img class="img-responsive img-border img-left" src="/assets/home-wall.jpg">
            <hr class="visible-xs">
            <p>It's time to get informed! Signing up for our newsletter will open the door to  exclusive package offerings, weekly & monthly deals, and preferred customer rewards. It will also help build sustainable relationships that will benefit both parties in the present and future. This environment will give us the ability to implement new services with your wishes and satisfaction in mind, as well as the opportunity to improve those already in place!</p>
          </div>
        </div>
      </div>
<section>
  <div class="column">
    <h2>Stay in touch.</h2>
  </div>
  <div class="column">
    <div class="form-centered">
      <%= simple_form_for @visitor do |f| %>
        <%= f.error_notification %>
        <%= f.input :email, label: false, :placeholder => 'Your email address...' %>
        <br/>
        <%= f.button :submit, "Sign Up Today", :class => "submit" %>
      <% end %>
    </div>
  </div>
</section>
<br>
<br>
    <script>
         // Activates the Carousel
         $('.carousel').carousel({
                interval: 2000
         })
    </script>